# rosrun wiimote wiimode_node.py
# /wiimote/classic
mappings:
  axes:
    - axes[0]
    - axes[1]
    - axes[2]
    - axes[3]
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0
  buttons:
    - buttons[5]
    - 0
    - 0
    - buttons[4]
    - buttons[8]
    - buttons[7]
    - buttons[9]
    - buttons[6]
    - buttons[13]
    - buttons[14]
    - buttons[11]
    - buttons[12]
    - buttons[0]
    - buttons[2]
    - buttons[3]
    - buttons[1]
    - buttons[10]
